[project]
name = "multisetp-form"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2.2",
    "django-crispy-forms>=2.4",
    "django-formtools>=2.5.1",
    "python-dotenv>=1.1.0",
    "twilio>=9.6.2",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "multisetp-form",
    "pylint>=3.3.7",
]

[tool.uv.sources]
multisetp-form = { workspace = true }
